name: "bap"

parameters:
  # VAP parameters
  epsilon: 32.0
  alpha: 1.0
  n_iters: 3000
  constrained: true
  batch_size: 2
  image_path: "attacks/data/clean.jpeg"  # Original clean image
  target_path: "attacks/data/corpus.txt"  # Corpus file path
  target_model: "minigpt4.minigpt4_model.MiniGPT4"
  device: "cuda"  # Auto detect
  
  # CoT parameters
  cot_model: "gpt-3.5-turbo"
  max_cot_iterations: 3
  load_model: true