name: "hades"

parameters:
  # === Image Generation Configuration ===
  pixart_path: "/mnt/disk1/weights/t2i/PixArt-alpha/PixArt-XL-2-1024-MS"
  creat_image: true
  iter_steps: 3  # Iteration steps

  # === Font Configuration ===
  font_path: "/mnt/disk1/szchen/VLMBenchmark/repo/OmniSafeBench-MM/attacks/Arial Font/ARIAL.TTF"
  font_size: 70

  # === API Configuration ===
  auxiliary_model_name: "gpt-3.5-turbo"
  load_model: true