name: "hades"

parameters:
  # === Image Generation Configuration ===
  pixart_path: "/path/to/PixArt-alpha/PixArt-XL-2-1024-MS"
  creat_image: true
  iter_steps: 3  # Iteration steps

  # === Font Configuration ===
  font_path: "attacks/Arial Font/ARIAL.TTF"
  font_size: 70

  # === API Configuration ===
  auxiliary_model_name: "gpt-3.5-turbo"
  load_model: true