name: "qr"

parameters:

  # SD model path
  stable_diffusion_path: "/mnt/disk1/weights/t2i/stable-diffusion-3.5-medium"
  
  # Rendering parameters
  font_size: 80
  max_width: 768
  font_path: "attacks/Arial Font/ARIAL.TTF"
  
  # Control options
  generate_sd_images: true
  
  # Auxiliary model configuration
  auxiliary_model_name: "gpt-3.5-turbo"
  load_model: true