evaluation:
  evaluator_params:
    default_judge:
      api_key: EMPTY
      base_url: http://localhost:8035/v1
      max_tokens: 2048
      model: gpt-oss-120b
      temperature: 0.0
  evaluators:
  - default_judge
experiment:
  mode: response_only
  random_seed: 42
  verbose: false
response_generation:
  defenses:
  - None
  models:
  - Kimi-VL-A3B-Instruct
system:
  batch_size: 8
  log_file: logs/experiment_0210.log
  log_level: INFO
  max_workers: 1
  output_dir: output/
test_case_generation:
  attacks:
  - cs_dj
  input:
    behaviors_file: /mnt/disk1/szchen/VLMBenchmark/repo/OmniSafeBench-MM/dataset/data_full.json
